#!/bin/sh
set -eu

HERE=${MAGICPAPER_RUNTIME_ROOT:-/home/root/apps/remagic/opt/magicpaper}
LEGACY=${MAGICPAPER_LEGACY_ROOT:-/home/root/apps/riddle}
LEGACY_CONFIG=${MAGICPAPER_LEGACY_CONFIG:-/home/root/.config/riddle/oracle.env}
ENV_LOADER=${MAGICPAPER_ENV_LOADER:-/home/root/apps/remagic/libexec/magicpaper-env}
CONFIG=${MAGICPAPER_CONFIG:-/home/root/.config/magicpaper/oracle.env}
umask 077
. "$ENV_LOADER"

load_magicpaper_config "$CONFIG" "$LEGACY_CONFIG" "$LEGACY/oracle.env" \
    "${MAGICPAPER_TEST_MODE:-0}"

cd "$HERE"
exec "$HERE/magicpaper" "$@"
