#!/bin/sh
set -eu

HERE=${MAGICPAPER_RUNTIME_ROOT:-/home/root/apps/remagic/opt/magicpaper}
LEGACY=${MAGICPAPER_LEGACY_ROOT:-/home/root/apps/riddle}
ENV_LOADER=${MAGICPAPER_ENV_LOADER:-/home/root/apps/remagic/libexec/riddle-env}
CONFIG=${RIDDLE_CONFIG:-/home/root/.config/riddle/oracle.env}
umask 077
. "$ENV_LOADER"

load_riddle_config "$CONFIG" "$LEGACY/oracle.env" "${RIDDLE_TEST_MODE:-0}"

cd "$HERE"
exec "$HERE/riddle-qtfb" "$@"
